changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Security and recovery
      labels:
        - security
        - recovery
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Other changes
      labels:
        - '*'
